In [3]:
import numpy as np

## create a numpy array

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


## creating 2 dimensional arrays and specifying the data type of array

In [11]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=np.int32)
print(b)
print(b.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32
